// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.Contatto;
import it.phrasebook.domain.ContattoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ContattoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContattoDataOnDemand: @Component;
    
    private Random ContattoDataOnDemand.rnd = new SecureRandom();
    
    private List<Contatto> ContattoDataOnDemand.data;
    
    public Contatto ContattoDataOnDemand.getNewTransientContatto(int index) {
        Contatto obj = new Contatto();
        setCognome(obj, index);
        setNome(obj, index);
        setTelefono(obj, index);
        return obj;
    }
    
    public void ContattoDataOnDemand.setCognome(Contatto obj, int index) {
        String cognome = "cognome_" + index;
        obj.setCognome(cognome);
    }
    
    public void ContattoDataOnDemand.setNome(Contatto obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void ContattoDataOnDemand.setTelefono(Contatto obj, int index) {
        String telefono = "telefono_" + index;
        obj.setTelefono(telefono);
    }
    
    public Contatto ContattoDataOnDemand.getSpecificContatto(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Contatto obj = data.get(index);
        Long id = obj.getId();
        return Contatto.findContatto(id);
    }
    
    public Contatto ContattoDataOnDemand.getRandomContatto() {
        init();
        Contatto obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Contatto.findContatto(id);
    }
    
    public boolean ContattoDataOnDemand.modifyContatto(Contatto obj) {
        return false;
    }
    
    public void ContattoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Contatto.findContattoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Contatto' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Contatto>();
        for (int i = 0; i < 10; i++) {
            Contatto obj = getNewTransientContatto(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
