// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.Editore;
import it.phrasebook.domain.EditoreDataOnDemand;
import it.phrasebook.domain.EditoreIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EditoreIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EditoreIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EditoreIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EditoreIntegrationTest: @Transactional;
    
    @Autowired
    private EditoreDataOnDemand EditoreIntegrationTest.dod;
    
    @Test
    public void EditoreIntegrationTest.testCountEditores() {
        Assert.assertNotNull("Data on demand for 'Editore' failed to initialize correctly", dod.getRandomEditore());
        long count = Editore.countEditores();
        Assert.assertTrue("Counter for 'Editore' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EditoreIntegrationTest.testFindEditore() {
        Editore obj = dod.getRandomEditore();
        Assert.assertNotNull("Data on demand for 'Editore' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Editore' failed to provide an identifier", id);
        obj = Editore.findEditore(id);
        Assert.assertNotNull("Find method for 'Editore' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Editore' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EditoreIntegrationTest.testFindAllEditores() {
        Assert.assertNotNull("Data on demand for 'Editore' failed to initialize correctly", dod.getRandomEditore());
        long count = Editore.countEditores();
        Assert.assertTrue("Too expensive to perform a find all test for 'Editore', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Editore> result = Editore.findAllEditores();
        Assert.assertNotNull("Find all method for 'Editore' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Editore' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EditoreIntegrationTest.testFindEditoreEntries() {
        Assert.assertNotNull("Data on demand for 'Editore' failed to initialize correctly", dod.getRandomEditore());
        long count = Editore.countEditores();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Editore> result = Editore.findEditoreEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Editore' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Editore' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EditoreIntegrationTest.testFlush() {
        Editore obj = dod.getRandomEditore();
        Assert.assertNotNull("Data on demand for 'Editore' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Editore' failed to provide an identifier", id);
        obj = Editore.findEditore(id);
        Assert.assertNotNull("Find method for 'Editore' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEditore(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Editore' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EditoreIntegrationTest.testMergeUpdate() {
        Editore obj = dod.getRandomEditore();
        Assert.assertNotNull("Data on demand for 'Editore' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Editore' failed to provide an identifier", id);
        obj = Editore.findEditore(id);
        boolean modified =  dod.modifyEditore(obj);
        Integer currentVersion = obj.getVersion();
        Editore merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Editore' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EditoreIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Editore' failed to initialize correctly", dod.getRandomEditore());
        Editore obj = dod.getNewTransientEditore(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Editore' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Editore' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Editore' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EditoreIntegrationTest.testRemove() {
        Editore obj = dod.getRandomEditore();
        Assert.assertNotNull("Data on demand for 'Editore' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Editore' failed to provide an identifier", id);
        obj = Editore.findEditore(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Editore' with identifier '" + id + "'", Editore.findEditore(id));
    }
    
}
