// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.Editore;
import it.phrasebook.domain.EditoreDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect EditoreDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EditoreDataOnDemand: @Component;
    
    private Random EditoreDataOnDemand.rnd = new SecureRandom();
    
    private List<Editore> EditoreDataOnDemand.data;
    
    public Editore EditoreDataOnDemand.getNewTransientEditore(int index) {
        Editore obj = new Editore();
        setCasaEditrice(obj, index);
        return obj;
    }
    
    public void EditoreDataOnDemand.setCasaEditrice(Editore obj, int index) {
        String casaEditrice = "casaEditrice_" + index;
        obj.setCasaEditrice(casaEditrice);
    }
    
    public Editore EditoreDataOnDemand.getSpecificEditore(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Editore obj = data.get(index);
        Long id = obj.getId();
        return Editore.findEditore(id);
    }
    
    public Editore EditoreDataOnDemand.getRandomEditore() {
        init();
        Editore obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Editore.findEditore(id);
    }
    
    public boolean EditoreDataOnDemand.modifyEditore(Editore obj) {
        return false;
    }
    
    public void EditoreDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Editore.findEditoreEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Editore' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Editore>();
        for (int i = 0; i < 10; i++) {
            Editore obj = getNewTransientEditore(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
