// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.Libro;
import it.phrasebook.domain.LibroDataOnDemand;
import it.phrasebook.domain.LibroIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LibroIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LibroIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LibroIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LibroIntegrationTest: @Transactional;
    
    @Autowired
    private LibroDataOnDemand LibroIntegrationTest.dod;
    
    @Test
    public void LibroIntegrationTest.testCountLibroes() {
        Assert.assertNotNull("Data on demand for 'Libro' failed to initialize correctly", dod.getRandomLibro());
        long count = Libro.countLibroes();
        Assert.assertTrue("Counter for 'Libro' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LibroIntegrationTest.testFindLibro() {
        Libro obj = dod.getRandomLibro();
        Assert.assertNotNull("Data on demand for 'Libro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Libro' failed to provide an identifier", id);
        obj = Libro.findLibro(id);
        Assert.assertNotNull("Find method for 'Libro' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Libro' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LibroIntegrationTest.testFindAllLibroes() {
        Assert.assertNotNull("Data on demand for 'Libro' failed to initialize correctly", dod.getRandomLibro());
        long count = Libro.countLibroes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Libro', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Libro> result = Libro.findAllLibroes();
        Assert.assertNotNull("Find all method for 'Libro' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Libro' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LibroIntegrationTest.testFindLibroEntries() {
        Assert.assertNotNull("Data on demand for 'Libro' failed to initialize correctly", dod.getRandomLibro());
        long count = Libro.countLibroes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Libro> result = Libro.findLibroEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Libro' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Libro' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LibroIntegrationTest.testFlush() {
        Libro obj = dod.getRandomLibro();
        Assert.assertNotNull("Data on demand for 'Libro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Libro' failed to provide an identifier", id);
        obj = Libro.findLibro(id);
        Assert.assertNotNull("Find method for 'Libro' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLibro(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Libro' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LibroIntegrationTest.testMergeUpdate() {
        Libro obj = dod.getRandomLibro();
        Assert.assertNotNull("Data on demand for 'Libro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Libro' failed to provide an identifier", id);
        obj = Libro.findLibro(id);
        boolean modified =  dod.modifyLibro(obj);
        Integer currentVersion = obj.getVersion();
        Libro merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Libro' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LibroIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Libro' failed to initialize correctly", dod.getRandomLibro());
        Libro obj = dod.getNewTransientLibro(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Libro' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Libro' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Libro' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LibroIntegrationTest.testRemove() {
        Libro obj = dod.getRandomLibro();
        Assert.assertNotNull("Data on demand for 'Libro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Libro' failed to provide an identifier", id);
        obj = Libro.findLibro(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Libro' with identifier '" + id + "'", Libro.findLibro(id));
    }
    
}
