// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.RichiestaVendita;
import it.phrasebook.domain.RichiestaVenditaDataOnDemand;
import it.phrasebook.domain.TipoRichiesta;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RichiestaVenditaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RichiestaVenditaDataOnDemand: @Component;
    
    private Random RichiestaVenditaDataOnDemand.rnd = new SecureRandom();
    
    private List<RichiestaVendita> RichiestaVenditaDataOnDemand.data;
    
    public RichiestaVendita RichiestaVenditaDataOnDemand.getNewTransientRichiestaVendita(int index) {
        RichiestaVendita obj = new RichiestaVendita();
        setDataRichiesta(obj, index);
        setNote(obj, index);
        setPrezzoCopertina(obj, index);
        setTipoRichiesta(obj, index);
        return obj;
    }
    
    public void RichiestaVenditaDataOnDemand.setDataRichiesta(RichiestaVendita obj, int index) {
        Date dataRichiesta = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDataRichiesta(dataRichiesta);
    }
    
    public void RichiestaVenditaDataOnDemand.setNote(RichiestaVendita obj, int index) {
        String note = "note_" + index;
        obj.setNote(note);
    }
    
    public void RichiestaVenditaDataOnDemand.setPrezzoCopertina(RichiestaVendita obj, int index) {
        BigDecimal prezzoCopertina = BigDecimal.valueOf(index);
        if (prezzoCopertina.compareTo(new BigDecimal("9999.99")) == 1) {
            prezzoCopertina = new BigDecimal("9999.99");
        }
        obj.setPrezzoCopertina(prezzoCopertina);
    }
    
    public void RichiestaVenditaDataOnDemand.setTipoRichiesta(RichiestaVendita obj, int index) {
        TipoRichiesta tipoRichiesta = TipoRichiesta.class.getEnumConstants()[0];
        obj.setTipoRichiesta(tipoRichiesta);
    }
    
    public RichiestaVendita RichiestaVenditaDataOnDemand.getSpecificRichiestaVendita(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        RichiestaVendita obj = data.get(index);
        Long id = obj.getId();
        return RichiestaVendita.findRichiestaVendita(id);
    }
    
    public RichiestaVendita RichiestaVenditaDataOnDemand.getRandomRichiestaVendita() {
        init();
        RichiestaVendita obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return RichiestaVendita.findRichiestaVendita(id);
    }
    
    public boolean RichiestaVenditaDataOnDemand.modifyRichiestaVendita(RichiestaVendita obj) {
        return false;
    }
    
    public void RichiestaVenditaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = RichiestaVendita.findRichiestaVenditaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'RichiestaVendita' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<RichiestaVendita>();
        for (int i = 0; i < 10; i++) {
            RichiestaVendita obj = getNewTransientRichiestaVendita(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
