// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.RichiestaAcquisto;
import it.phrasebook.domain.RichiestaAcquistoDataOnDemand;
import it.phrasebook.domain.RichiestaAcquistoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RichiestaAcquistoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RichiestaAcquistoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RichiestaAcquistoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RichiestaAcquistoIntegrationTest: @Transactional;
    
    @Autowired
    private RichiestaAcquistoDataOnDemand RichiestaAcquistoIntegrationTest.dod;
    
    @Test
    public void RichiestaAcquistoIntegrationTest.testCountRichiestaAcquistoes() {
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to initialize correctly", dod.getRandomRichiestaAcquisto());
        long count = RichiestaAcquisto.countRichiestaAcquistoes();
        Assert.assertTrue("Counter for 'RichiestaAcquisto' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RichiestaAcquistoIntegrationTest.testFindRichiestaAcquisto() {
        RichiestaAcquisto obj = dod.getRandomRichiestaAcquisto();
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to provide an identifier", id);
        obj = RichiestaAcquisto.findRichiestaAcquisto(id);
        Assert.assertNotNull("Find method for 'RichiestaAcquisto' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RichiestaAcquisto' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RichiestaAcquistoIntegrationTest.testFindAllRichiestaAcquistoes() {
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to initialize correctly", dod.getRandomRichiestaAcquisto());
        long count = RichiestaAcquisto.countRichiestaAcquistoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'RichiestaAcquisto', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RichiestaAcquisto> result = RichiestaAcquisto.findAllRichiestaAcquistoes();
        Assert.assertNotNull("Find all method for 'RichiestaAcquisto' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RichiestaAcquisto' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RichiestaAcquistoIntegrationTest.testFindRichiestaAcquistoEntries() {
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to initialize correctly", dod.getRandomRichiestaAcquisto());
        long count = RichiestaAcquisto.countRichiestaAcquistoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RichiestaAcquisto> result = RichiestaAcquisto.findRichiestaAcquistoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RichiestaAcquisto' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RichiestaAcquisto' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RichiestaAcquistoIntegrationTest.testFlush() {
        RichiestaAcquisto obj = dod.getRandomRichiestaAcquisto();
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to provide an identifier", id);
        obj = RichiestaAcquisto.findRichiestaAcquisto(id);
        Assert.assertNotNull("Find method for 'RichiestaAcquisto' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRichiestaAcquisto(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RichiestaAcquisto' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RichiestaAcquistoIntegrationTest.testMergeUpdate() {
        RichiestaAcquisto obj = dod.getRandomRichiestaAcquisto();
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to provide an identifier", id);
        obj = RichiestaAcquisto.findRichiestaAcquisto(id);
        boolean modified =  dod.modifyRichiestaAcquisto(obj);
        Integer currentVersion = obj.getVersion();
        RichiestaAcquisto merged = (RichiestaAcquisto)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RichiestaAcquisto' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RichiestaAcquistoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to initialize correctly", dod.getRandomRichiestaAcquisto());
        RichiestaAcquisto obj = dod.getNewTransientRichiestaAcquisto(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RichiestaAcquisto' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RichiestaAcquisto' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RichiestaAcquistoIntegrationTest.testRemove() {
        RichiestaAcquisto obj = dod.getRandomRichiestaAcquisto();
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RichiestaAcquisto' failed to provide an identifier", id);
        obj = RichiestaAcquisto.findRichiestaAcquisto(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RichiestaAcquisto' with identifier '" + id + "'", RichiestaAcquisto.findRichiestaAcquisto(id));
    }
    
}
