// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.RichiestaVendita;
import it.phrasebook.domain.RichiestaVenditaDataOnDemand;
import it.phrasebook.domain.RichiestaVenditaIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RichiestaVenditaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RichiestaVenditaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RichiestaVenditaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RichiestaVenditaIntegrationTest: @Transactional;
    
    @Autowired
    private RichiestaVenditaDataOnDemand RichiestaVenditaIntegrationTest.dod;
    
    @Test
    public void RichiestaVenditaIntegrationTest.testCountRichiestaVenditas() {
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to initialize correctly", dod.getRandomRichiestaVendita());
        long count = RichiestaVendita.countRichiestaVenditas();
        Assert.assertTrue("Counter for 'RichiestaVendita' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RichiestaVenditaIntegrationTest.testFindRichiestaVendita() {
        RichiestaVendita obj = dod.getRandomRichiestaVendita();
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to provide an identifier", id);
        obj = RichiestaVendita.findRichiestaVendita(id);
        Assert.assertNotNull("Find method for 'RichiestaVendita' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RichiestaVendita' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RichiestaVenditaIntegrationTest.testFindAllRichiestaVenditas() {
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to initialize correctly", dod.getRandomRichiestaVendita());
        long count = RichiestaVendita.countRichiestaVenditas();
        Assert.assertTrue("Too expensive to perform a find all test for 'RichiestaVendita', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RichiestaVendita> result = RichiestaVendita.findAllRichiestaVenditas();
        Assert.assertNotNull("Find all method for 'RichiestaVendita' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RichiestaVendita' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RichiestaVenditaIntegrationTest.testFindRichiestaVenditaEntries() {
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to initialize correctly", dod.getRandomRichiestaVendita());
        long count = RichiestaVendita.countRichiestaVenditas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RichiestaVendita> result = RichiestaVendita.findRichiestaVenditaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RichiestaVendita' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RichiestaVendita' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RichiestaVenditaIntegrationTest.testFlush() {
        RichiestaVendita obj = dod.getRandomRichiestaVendita();
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to provide an identifier", id);
        obj = RichiestaVendita.findRichiestaVendita(id);
        Assert.assertNotNull("Find method for 'RichiestaVendita' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRichiestaVendita(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RichiestaVendita' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RichiestaVenditaIntegrationTest.testMergeUpdate() {
        RichiestaVendita obj = dod.getRandomRichiestaVendita();
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to provide an identifier", id);
        obj = RichiestaVendita.findRichiestaVendita(id);
        boolean modified =  dod.modifyRichiestaVendita(obj);
        Integer currentVersion = obj.getVersion();
        RichiestaVendita merged = (RichiestaVendita)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RichiestaVendita' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RichiestaVenditaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to initialize correctly", dod.getRandomRichiestaVendita());
        RichiestaVendita obj = dod.getNewTransientRichiestaVendita(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RichiestaVendita' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RichiestaVendita' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RichiestaVenditaIntegrationTest.testRemove() {
        RichiestaVendita obj = dod.getRandomRichiestaVendita();
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RichiestaVendita' failed to provide an identifier", id);
        obj = RichiestaVendita.findRichiestaVendita(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RichiestaVendita' with identifier '" + id + "'", RichiestaVendita.findRichiestaVendita(id));
    }
    
}
