// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.Editore;

privileged aspect Editore_Roo_JavaBean {
    
    public String Editore.getCasaEditrice() {
        return this.casaEditrice;
    }
    
    public void Editore.setCasaEditrice(String casaEditrice) {
        this.casaEditrice = casaEditrice;
    }
    
}
