// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.Libro;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Libro_Roo_Configurable {
    
    declare @type: Libro: @Configurable;
    
}
