// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.phrasebook.domain;

import it.phrasebook.domain.RichiestaAcquisto;
import javax.persistence.Entity;

privileged aspect RichiestaAcquisto_Roo_Jpa_Entity {
    
    declare @type: RichiestaAcquisto: @Entity;
    
}
